<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import hotelTrainingHero from './assets/hotel-training-hero-v2.png'

const canvas = ref(null)
const active = ref(0)
const activeGroup = ref('IT i technologia')
const progress = ref(0)
const sent = ref(false)
const inquiryOpen = ref(false)
const inquirySent = ref(false)
let frame

const courses = [
  { group:'IT i technologia', code:'AI', category:'AI / CYFRYZACJA', title:'AI w pracy biurowej', lead:'Od pierwszego promptu do bezpiecznego procesu w organizacji.', format:'ONLINE / W FIRMIE', scope:'PROGRAM 1-DNIOWY', color:'#d9ff57', trainer:'Ekspert wdrożeniowy AI', role:'Praktyka, bezpieczeństwo, automatyzacja', description:'Szkolenie dla zespołów, które chcą wykorzystywać generatywną AI w codziennej pracy bez chaosu i ryzyka.', points:['analiza dokumentów i research','bezpieczeństwo informacji','automatyzacja codziennych zadań'] },
  { group:'IT i technologia', code:'CY', category:'CYBERBEZPIECZEŃSTWO', title:'Cyberbezpieczeństwo pracowników', lead:'Nawyki, które realnie ograniczają ryzyko incydentu.', format:'ONLINE / W FIRMIE', scope:'PROGRAM 1-DNIOWY', color:'#72e6ca', trainer:'Ekspert cyberbezpieczeństwa', role:'SOC, incydenty, świadomość użytkowników', description:'Praktyczny program budujący odporność zespołu na phishing, wyłudzenia, utratę danych i błędy codziennej pracy.', points:['phishing i socjotechnika','bezpieczna praca z danymi','reakcja na incydent'] },
  { group:'Prawo', code:'PZ', category:'ZAMÓWIENIA PUBLICZNE', title:'Umowy w zamówieniach', lead:'Klauzule, waloryzacja i odpowiedzialność stron bez niedomówień.', format:'ONLINE / W FIRMIE', scope:'PROGRAM 2-DNIOWY', color:'#86cfff', trainer:'Radca prawny / ekspert PZP', role:'Umowy, postępowania, spory', description:'Warsztat dla zamawiających i wykonawców dotyczący konstrukcji umowy, dopuszczalnych zmian i sporów.', points:['projektowanie bezpiecznych klauzul','zmiany i odstąpienie od umowy','spory oraz odpowiedzialność'] },
  { group:'Prawo', code:'RO', category:'RODO / COMPLIANCE', title:'RODO w codziennej praktyce', lead:'Obowiązki przełożone na procesy, dokumenty i decyzje.', format:'ONLINE / W FIRMIE', scope:'PROGRAM 1-DNIOWY', color:'#7bbcff', trainer:'Prawnik ochrony danych', role:'RODO, compliance, audyty', description:'Program dla osób przetwarzających dane i właścicieli procesów, oparty na realnych sytuacjach organizacji.', points:['podstawy legalnego przetwarzania','naruszenia i reakcja','dokumentacja oraz odpowiedzialność'] },
  { group:'Finanse', code:'KF', category:'FINANSE / PODATKI', title:'KSeF od podstaw', lead:'Zrozum system, uporządkuj role i przygotuj firmę do zmiany.', format:'ONLINE / W FIRMIE', scope:'PROGRAM 1-DNIOWY', color:'#ffb86b', trainer:'Doradca podatkowy', role:'Podatki, procesy finansowe, KSeF', description:'Przejście od wymagań prawnych do praktycznej mapy procesu fakturowania w organizacji.', points:['obieg i akceptacja faktur','uprawnienia oraz tokeny','plan gotowości organizacji'] },
  { group:'Finanse', code:'EX', category:'ANALIZA DANYCH', title:'Excel dla finansów', lead:'Analiza, kontrola i raportowanie bez ręcznej pracy.', format:'ONLINE / W FIRMIE', scope:'PROGRAM 2-DNIOWY', color:'#ffc875', trainer:'Analityk finansowy', role:'Excel, Power Query, raportowanie', description:'Warsztat pracy z danymi dla osób przygotowujących raporty, zestawienia i analizy finansowe.', points:['porządkowanie danych','formuły i tabele przestawne','automatyzacja raportów'] },
  { group:'HR i zarządzanie', code:'HR', category:'HR / PRAWO PRACY', title:'Prawo pracy dla pracodawców', lead:'Przepisy przełożone na dokumenty, procedury i decyzje HR.', format:'ONLINE / W FIRMIE', scope:'PROGRAM 1-DNIOWY', color:'#c9b4ff', trainer:'Radca prawny prawa pracy', role:'Kadry, HR, relacje pracownicze', description:'Aktualny program dla osób odpowiedzialnych za kadry i zarządzanie zespołem.', points:['obowiązki pracodawców','dokumentacja i procedury','checklista dla działu HR'] },
  { group:'HR i zarządzanie', code:'LD', category:'ZARZĄDZANIE', title:'Lider w zmianie', lead:'Komunikacja, decyzje i odpowiedzialność w wymagającym środowisku.', format:'W FIRMIE', scope:'PROGRAM 2-DNIOWY', color:'#e3b8ff', trainer:'Trener zarządzania', role:'Przywództwo, zespoły, zmiana', description:'Intensywny warsztat dla menedżerów prowadzących zespoły przez reorganizację i zmianę sposobu pracy.', points:['komunikowanie zmiany','praca z oporem','kontrakt i odpowiedzialność zespołu'] },
  { group:'Administracja', code:'KP', category:'POSTĘPOWANIE ADMINISTRACYJNE', title:'KPA w praktyce urzędu', lead:'Postępowanie prowadzone sprawnie, poprawnie i czytelnie.', format:'ONLINE / W INSTYTUCJI', scope:'PROGRAM 2-DNIOWY', color:'#95dfb4', trainer:'Prawnik administratywista', role:'KPA, samorząd, procedury', description:'Kompleksowe szkolenie dla pracowników administracji prowadzących postępowania i przygotowujących decyzje.', points:['wszczęcie i terminy','postępowanie dowodowe','decyzje i tryby odwoławcze'] },
  { group:'ESG i środowisko', code:'ES', category:'ESG / RAPORTOWANIE', title:'ESG w praktyce organizacji', lead:'Od obowiązku do uporządkowanego procesu i wiarygodnych danych.', format:'ONLINE / W FIRMIE', scope:'PROGRAM 1-DNIOWY', color:'#a7e57a', trainer:'Ekspert raportowania ESG', role:'ESG, dane, compliance', description:'Program pomaga zrozumieć wymagania, zbudować mapę odpowiedzialności i rozpocząć zbieranie danych.', points:['zakres raportowania','właściciele danych','plan wdrożenia procesu'] },
  { group:'IT i technologia', code:'MS', category:'MICROSOFT 365', title:'Microsoft 365 w pracy zespołu', lead:'Lepsza współpraca, porządek w plikach i mniej ręcznych czynności.', format:'ONLINE / W FIRMIE', scope:'PROGRAM 1-DNIOWY', color:'#72b7ff', trainer:'Trener narzędzi Microsoft', role:'Teams, SharePoint, automatyzacja', description:'Warsztat porządkujący codzienną współpracę w środowisku Microsoft 365 i pokazujący praktyczne automatyzacje.', points:['Teams i współpraca','SharePoint oraz pliki','proste automatyzacje'] },
  { group:'IT i technologia', code:'DA', category:'DANE / ANALITYKA', title:'Power BI od podstaw', lead:'Od surowych danych do czytelnego raportu wspierającego decyzje.', format:'ONLINE / W FIRMIE', scope:'PROGRAM 2-DNIOWY', color:'#5cd8ed', trainer:'Analityk danych', role:'Power BI, modele danych, dashboardy', description:'Uczestnicy budują pierwszy kompletny raport: od importu i porządkowania danych po wizualizację wyników.', points:['przygotowanie danych','model i podstawy DAX','czytelny dashboard'] },
  { group:'Prawo', code:'UM', category:'PRAWO GOSPODARCZE', title:'Umowy w obrocie gospodarczym', lead:'Jak zabezpieczyć interes firmy i ograniczyć ryzyko kontraktowe.', format:'ONLINE / W FIRMIE', scope:'PROGRAM 2-DNIOWY', color:'#78aef2', trainer:'Radca prawny', role:'Kontrakty, negocjacje, odpowiedzialność', description:'Praktyczne szkolenie z tworzenia, analizowania i negocjowania najczęściej spotykanych umów biznesowych.', points:['kluczowe postanowienia','odpowiedzialność i kary','zmiana oraz rozwiązanie umowy'] },
  { group:'Prawo', code:'SY', category:'OCHRONA SYGNALISTÓW', title:'Postępowania po zgłoszeniu sygnalisty', lead:'Od przyjęcia zgłoszenia do bezpiecznego zamknięcia sprawy.', format:'ONLINE / W FIRMIE', scope:'PROGRAM 1-DNIOWY', color:'#69c2ed', trainer:'Prawnik compliance', role:'Sygnaliści, postępowania, etyka', description:'Program dla osób przyjmujących zgłoszenia i prowadzących postępowania wyjaśniające w organizacji.', points:['kwalifikacja zgłoszenia','postępowanie wyjaśniające','ochrona i dokumentacja'] },
  { group:'Finanse', code:'VA', category:'VAT / PODATKI', title:'VAT w transakcjach krajowych', lead:'Najczęstsze problemy rozliczeń wyjaśnione na praktycznych przykładach.', format:'ONLINE / W FIRMIE', scope:'PROGRAM 1-DNIOWY', color:'#ffa867', trainer:'Doradca podatkowy', role:'VAT, faktury, rozliczenia', description:'Aktualne zasady VAT dla osób wystawiających i rozliczających dokumenty sprzedażowe oraz zakupowe.', points:['moment obowiązku podatkowego','odliczenie i korekty','trudne przypadki fakturowania'] },
  { group:'Finanse', code:'BU', category:'BUDŻETOWANIE', title:'Budżet i controlling operacyjny', lead:'Planowanie, analiza odchyleń i raportowanie dla menedżerów.', format:'ONLINE / W FIRMIE', scope:'PROGRAM 2-DNIOWY', color:'#f0bd62', trainer:'Kontroler finansowy', role:'Budżetowanie, controlling, raporty', description:'Warsztat budowy budżetu oraz interpretacji wyników dla osób odpowiedzialnych za koszty i realizację planu.', points:['struktura budżetu','analiza odchyleń','raport zarządczy'] },
  { group:'HR i zarządzanie', code:'KM', category:'KOMUNIKACJA', title:'Trudne rozmowy menedżerskie', lead:'Jak mówić jasno, stawiać granice i utrzymywać dobrą relację.', format:'W FIRMIE', scope:'PROGRAM 1-DNIOWY', color:'#c9aef5', trainer:'Trener komunikacji', role:'Feedback, konflikty, rozmowy', description:'Ćwiczeniowy program dla menedżerów prowadzących rozmowy o wynikach, zachowaniu i zmianie.', points:['struktura trudnej rozmowy','informacja zwrotna','reakcja na opór i emocje'] },
  { group:'HR i zarządzanie', code:'RE', category:'REKRUTACJA', title:'Skuteczna rekrutacja i selekcja', lead:'Lepsze pytania, trafniejsze decyzje i spójne doświadczenie kandydata.', format:'ONLINE / W FIRMIE', scope:'PROGRAM 1-DNIOWY', color:'#bfa3ed', trainer:'Ekspert rekrutacji', role:'Wywiad, selekcja, candidate experience', description:'Program dla rekruterów i menedżerów zatrudniających, oparty na ustrukturyzowanym wywiadzie.', points:['profil kompetencyjny','pytania behawioralne','ocena i decyzja'] },
  { group:'Administracja', code:'DO', category:'DOSTĘPNOŚĆ', title:'Dostępność cyfrowa i WCAG', lead:'Dokumenty i usługi cyfrowe dostępne dla wszystkich użytkowników.', format:'ONLINE / W INSTYTUCJI', scope:'PROGRAM 1-DNIOWY', color:'#79d9ad', trainer:'Ekspert dostępności cyfrowej', role:'WCAG, dokumenty, serwisy', description:'Praktyczne przygotowanie treści, dokumentów i prostych interfejsów zgodnie z zasadami dostępności.', points:['podstawy WCAG','dostępne dokumenty','kontrola publikowanych treści'] },
  { group:'Administracja', code:'FU', category:'FUNDUSZE PUBLICZNE', title:'Kontrola projektów unijnych', lead:'Dokumentacja, kwalifikowalność i przygotowanie do kontroli projektu.', format:'ONLINE / W INSTYTUCJI', scope:'PROGRAM 2-DNIOWY', color:'#6bcea2', trainer:'Ekspert funduszy UE', role:'Projekty, wydatki, kontrole', description:'Szkolenie dla zespołów realizujących projekty współfinansowane i odpowiadających za ich dokumentację.', points:['kwalifikowalność wydatków','ścieżka audytowa','przebieg i wynik kontroli'] },
  { group:'Administracja', code:'AR', category:'ARCHIWIZACJA', title:'Instrukcja kancelaryjna w praktyce', lead:'Sprawny obieg, klasyfikacja i archiwizacja dokumentacji.', format:'ONLINE / W INSTYTUCJI', scope:'PROGRAM 1-DNIOWY', color:'#8acfb9', trainer:'Archiwista i praktyk administracji', role:'EZD, JRWA, dokumentacja', description:'Program porządkujący pracę kancelaryjną od wpływu dokumentu do przekazania materiałów do archiwum.', points:['rejestracja i dekretacja','klasyfikacja JRWA','archiwizacja dokumentacji'] },
  { group:'ESG i środowisko', code:'OD', category:'ODPADY / BDO', title:'Gospodarka odpadami i BDO', lead:'Obowiązki przedsiębiorcy, ewidencja i odpowiedzialność bez luk.', format:'ONLINE / W FIRMIE', scope:'PROGRAM 1-DNIOWY', color:'#82d86e', trainer:'Ekspert prawa środowiskowego', role:'Odpady, BDO, kontrole', description:'Aktualne obowiązki wytwórców i posiadaczy odpadów wraz z praktyką prowadzenia ewidencji.', points:['klasyfikacja odpadów','ewidencja w BDO','kontrole i odpowiedzialność'] },
  { group:'ESG i środowisko', code:'ŚL', category:'ŚLAD WĘGLOWY', title:'Ślad węglowy organizacji', lead:'Jak zebrać dane, policzyć emisje i zaplanować redukcję.', format:'ONLINE / W FIRMIE', scope:'PROGRAM 2-DNIOWY', color:'#69c97c', trainer:'Analityk klimatyczny', role:'GHG Protocol, emisje, dane', description:'Warsztat prowadzący przez granice kalkulacji, źródła danych i obliczenia emisji organizacji.', points:['zakresy emisji GHG','zbieranie i jakość danych','plan redukcji emisji'] },
  { group:'ESG i środowisko', code:'OP', category:'OPAKOWANIA / EPR', title:'Obowiązki opakowaniowe przedsiębiorcy', lead:'Ewidencja, sprawozdawczość i odpowiedzialność w praktyce.', format:'ONLINE / W FIRMIE', scope:'PROGRAM 1-DNIOWY', color:'#92d65c', trainer:'Ekspert gospodarki opakowaniami', role:'EPR, opakowania, sprawozdania', description:'Szkolenie dla firm wprowadzających produkty w opakowaniach i odpowiadających za ewidencję oraz rozliczenia.', points:['status wprowadzającego','ewidencja opakowań','sprawozdania i opłaty'] }
]
const groups = [
  {name:'IT i technologia',code:'01',icon:'⌘',text:'AI, cyberbezpieczeństwo i narzędzia cyfrowe'},
  {name:'Prawo',code:'02',icon:'§',text:'Umowy, compliance i regulacje'},
  {name:'Finanse',code:'03',icon:'%',text:'Podatki, KSeF i analiza danych'},
  {name:'HR i zarządzanie',code:'04',icon:'↗',text:'Prawo pracy, zespoły i przywództwo'},
  {name:'Administracja',code:'05',icon:'◇',text:'KPA, samorząd i procedury publiczne'},
  {name:'ESG i środowisko',code:'06',icon:'○',text:'Raportowanie, dane i odpowiedzialność'}
]
const current = computed(() => courses[active.value])
const groupCourses = computed(() => courses.filter(c => c.group === activeGroup.value))

const select = (index) => { active.value=index; activeGroup.value=courses[index].group; document.querySelector('#experience')?.scrollIntoView({behavior:'smooth'}) }
const selectGroup = (group) => { activeGroup.value=group; requestAnimationFrame(()=>document.querySelector('#trainings')?.scrollIntoView({behavior:'smooth'})) }
const handleScroll = () => { progress.value = window.scrollY / (document.documentElement.scrollHeight - innerHeight) * 100 }

onMounted(() => {
  const el=canvas.value, ctx=el.getContext('2d'); let points=[]; const pointer={x:innerWidth*.65,y:innerHeight*.4}
  const resize=()=>{el.width=innerWidth*devicePixelRatio;el.height=innerHeight*devicePixelRatio;el.style.width=`${innerWidth}px`;el.style.height=`${innerHeight}px`;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);points=Array.from({length:54},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.16,vy:(Math.random()-.5)*.16,r:Math.random()*1.6+.4}))}
  const move=e=>{pointer.x=e.clientX;pointer.y=e.clientY}
  const draw=()=>{ctx.clearRect(0,0,innerWidth,innerHeight);points.forEach((p,i)=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>innerWidth)p.vx*=-1;if(p.y<0||p.y>innerHeight)p.vy*=-1;for(let j=i+1;j<points.length;j++){const q=points[j],d=Math.hypot(p.x-q.x,p.y-q.y);if(d<150){ctx.strokeStyle=`rgba(67,142,255,${(1-d/150)*.12})`;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}}const d=Math.hypot(p.x-pointer.x,p.y-pointer.y);ctx.fillStyle=d<220?'rgba(111,228,255,.7)':'rgba(76,126,190,.2)';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});frame=requestAnimationFrame(draw)}
  resize();draw();addEventListener('resize',resize);addEventListener('pointermove',move);addEventListener('scroll',handleScroll)
  onBeforeUnmount(()=>{cancelAnimationFrame(frame);removeEventListener('resize',resize);removeEventListener('pointermove',move);removeEventListener('scroll',handleScroll)})
})
</script>

<template>
  <div class="world" :style="{'--course':current.color}">
    <canvas ref="canvas" class="network" aria-hidden="true"></canvas>
    <div class="noise"></div><div class="scroll-progress" :style="{width:`${progress}%`}"></div>
    <header class="hud">
      <a class="logo imperial-logo" href="#top"><svg viewBox="0 0 260 235" aria-hidden="true"><path class="logo-crown" d="M52 77 45 24l46 31 39-50 39 50 46-31-7 53"/><path class="logo-book" d="M20 105q62-25 110 21 48-46 110-21v93q-62-24-110 28-48-52-110-28Z"/><path class="logo-spine" d="M130 139v76"/><path class="logo-text-lines" d="M49 139q33-4 63 15m36 0q30-19 63-15M49 171q33-4 63 15m36 0q30-19 63-15"/></svg><span><strong>IMPERIAL</strong><br><b>ACADEMY</b></span></a>
    </header>

    <main id="top">
      <section class="portal">
        <div class="hero-film"><img :src="hotelTrainingHero" alt="Szkolenie biznesowe w eleganckiej sali konferencyjnej hotelu"/><div class="film-shade"></div><button aria-label="Przejdź do opisu naszego podejścia" @click="document.querySelector('#method')?.scrollIntoView({behavior:'smooth'})"><b>▶</b><span>POZNAJ NASZE<br>PODEJŚCIE</span></button></div>
        <div class="portal-copy"><h1 class="hero-claim">Budujemy imperia<br><em>razem z naszymi klientami.</em></h1><p>Specjalistyczne szkolenia dla ludzi, którzy podejmują decyzje w świecie ciągłej zmiany.</p><div class="training-options"><strong>Programy otwarte i zamknięte</strong><span>Online lub stacjonarnie</span></div><a href="#calendar">POZNAJ PROGRAMY <i>↓</i></a></div>
        <div class="portal-foot"><span>PRZEWIŃ, ABY ODKRYĆ</span><i></i></div>
      </section>

      <section id="calendar" class="calendar-scene category-scene"><header><h2 class="category-title">KATEGORIE</h2></header><div class="group-grid"><button v-for="group in groups" :key="group.name" :class="{active:activeGroup===group.name}" @click="selectGroup(group.name)"><svg class="category-art" viewBox="0 0 180 100" aria-hidden="true">
        <g v-if="group.code==='01'"><circle cx="32" cy="52" r="11"/><circle cx="92" cy="25" r="8"/><circle cx="145" cy="63" r="13"/><path d="M42 47 84 29M99 30l35 25M43 57l89 7"/><path d="M24 79h48M112 84h44"/></g>
        <g v-else-if="group.code==='02'"><path d="M90 16v68M55 28h70M68 31 48 70h40L68 31ZM112 31 92 70h40l-20-39ZM63 84h54"/><circle cx="90" cy="16" r="4"/></g>
        <g v-else-if="group.code==='03'"><path d="M27 78V52h20v26M61 78V39h20v39M95 78V26h20v52M129 78V14h20v64M22 78h132"/><path d="m30 37 34-13 33 4 45-20"/></g>
        <g v-else-if="group.code==='04'"><circle cx="90" cy="28" r="13"/><circle cx="43" cy="51" r="10"/><circle cx="137" cy="51" r="10"/><path d="M68 85c2-18 9-29 22-29s20 11 22 29M25 84c2-14 8-23 18-23 9 0 15 7 18 18M119 79c3-11 9-18 18-18 10 0 16 9 18 23"/></g>
        <g v-else-if="group.code==='05'"><path d="m25 37 65-25 65 25H25ZM34 43h112M42 43v38M66 43v38M90 43v38M114 43v38M138 43v38M27 82h126M20 89h140"/></g>
        <g v-else><path d="M90 86C54 77 42 50 56 22c31 2 55 17 58 44-1 12-8 19-24 20Z"/><path d="M61 30c13 17 23 33 29 56M94 47c13-7 24-9 35-5M105 70c16 2 29-2 38-12"/><circle cx="143" cy="58" r="7"/></g>
      </svg><h3>{{group.name}}</h3><p>{{group.text}}</p><i>↗</i></button></div></section>

      <section id="trainings" class="training-browser"><header><div><span class="chapter">SZKOLENIA / {{activeGroup}}</span><h2>Wybierz program.</h2></div><button @click="document.querySelector('#calendar')?.scrollIntoView({behavior:'smooth'})">ZMIEŃ KATEGORIĘ ↑</button></header><div><button v-for="course in groupCourses" :key="course.title" :style="{'--accent':course.color}" @click="select(courses.indexOf(course))"><span class="training-code">{{course.code}}</span><div><small>{{course.category}}</small><h3>{{course.title}}</h3><p>{{course.lead}}</p></div><em>{{course.scope}}<br>{{course.format}}</em><i>↗</i></button></div></section>

      <section id="experience" class="program-scene"><nav class="program-switcher" aria-label="Przełącz program szkoleniowy"><button v-for="course in groupCourses" :key="course.title" :class="{active:courses.indexOf(course)===active}" :style="{'--accent':course.color}" @click="active=courses.indexOf(course)"><span>{{course.code}}</span><b>{{course.title}}</b></button></nav><header><span class="chapter">WYBRANY PROGRAM</span><p>{{current.category}}</p></header><div class="program-title"><div class="program-date"><b>{{current.code}}</b><span>{{current.group}}</span></div><h2>{{current.title}}</h2><p>{{current.description}}</p></div><div class="program-data"><div><span>PROWADZENIE</span><b>{{current.trainer}}</b><small>{{current.role}}</small></div><div><span>FORMA</span><b>{{current.format}}</b><small>na żywo z prowadzącym</small></div><div><span>ZAKRES</span><b>{{current.scope}}</b><small>dopasujemy do poziomu grupy</small></div></div><ol><li v-for="point in current.points" :key="point"><span>{{point}}</span></li></ol><aside><div><span>PROGRAM DLA OSÓB I FIRM</span><strong>Chcesz zrealizować to szkolenie?</strong><p>Ustalimy termin, formę, poziom zaawansowania oraz zakres odpowiadający Twojej grupie.</p></div><button class="program-inquiry" @click="inquirySent=false;inquiryOpen=true">ZAPYTAJ O TERMIN I WYCENĘ <b>↗</b></button></aside></section>

      <section id="method" class="method-scene"><div class="method-statement"><span class="chapter">JAK PRACUJEMY</span><h2>Nie oglądasz.<br><em>Uczestniczysz.</em></h2><p>Każdy program ma jasny cel, przejrzystą agendę i konkretne rezultaty. Możemy zmienić zakres, poziom oraz przykłady tak, aby szkolenie odpowiadało sytuacji Twojej organizacji.</p></div><div class="method-path"><article><b>AGENDA</b><span>przed szkoleniem</span><h3>Wiesz dokładnie, czego się nauczysz</h3><p>Otrzymujesz czytelną agendę, cele modułów i informacje organizacyjne. Przy szkoleniu zamkniętym wcześniej zbieramy potrzeby zespołu.</p></article><article><b>NARZĘDZIA</b><span>online i na sali</span><h3>Technologia wspiera aktywną pracę</h3><p>Spotkania online prowadzimy na Microsoft Teams lub Zoom. Wykorzystujemy udostępnianie ekranu, pokoje warsztatowe, ankiety, tablice i pliki robocze.</p></article><article><b>PRAKTYKA</b><span>w trakcie</span><h3>Pracujesz na przykładach i pytaniach</h3><p>Prowadzący łączy omówienie tematu z ćwiczeniami, analizą przypadków i dyskusją. Uczestnicy mogą konsultować własne sytuacje.</p></article><article><b>DOPASOWANIE</b><span>dla Twojej firmy</span><h3>Program może powstać wokół potrzeb klienta</h3><p>Dostosujemy czas, poziom zaawansowania, branżowe przykłady i materiały. Po szkoleniu uczestnicy otrzymują materiały, narzędzia oraz certyfikat.</p></article></div></section>

      <section id="contact" class="contact-scene"><div><span class="chapter">KONTAKT</span><h2>Porozmawiajmy<br>o wiedzy.</h2><p>Nie potrzebujesz gotowego tytułu. Opisz zmianę, ryzyko albo kompetencję. Przygotujemy propozycję tematu, formy i zakresu.</p><div class="direct-contact"><a href="mailto:kontakt@imperialacademy.pl"><span>E-MAIL</span><b>kontakt@imperialacademy.pl</b></a><a href="tel:+48220000000"><span>TELEFON</span><b>+48 22 000 00 00</b></a><p><span>GODZINY KONTAKTU</span><b>pon.—pt. / 8:00—16:00</b></p></div></div><form @submit.prevent="sent=true"><template v-if="!sent"><header class="form-intro"><span>FORMULARZ KONTAKTOWY</span><h3>Napisz do nas</h3><p>Uzupełnij pola, a przygotujemy odpowiedź dopasowaną do Twojej sytuacji.</p></header><label><b>Imię i nazwisko</b><input required placeholder="np. Anna Kowalska"/></label><label><b>E-mail służbowy</b><input required type="email" placeholder="anna@firma.pl"/></label><label><b>Firma lub instytucja</b><input placeholder="Nazwa organizacji"/></label><label><b>Jakiego szkolenia potrzebujesz?</b><textarea required rows="4" placeholder="Opisz temat, problem, liczbę uczestników lub preferowaną formę..."></textarea></label><button>WYŚLIJ ZAPYTANIE <b>↗</b></button><small>Odpowiemy w ciągu jednego dnia roboczego.</small></template><div v-else class="sent"><b>✓</b><h3>Wiadomość odebrana.</h3><p>Wrócimy z propozycją w ciągu jednego dnia roboczego.</p></div></form></section>
    </main>
    <Teleport to="body"><div v-if="inquiryOpen" class="inquiry-modal" role="dialog" aria-modal="true" aria-labelledby="inquiry-title" @click.self="inquiryOpen=false"><div class="inquiry-window"><button class="modal-close" aria-label="Zamknij" @click="inquiryOpen=false">×</button><template v-if="!inquirySent"><header><span>ZAPYTANIE O KONKRETNE SZKOLENIE</span><h2 id="inquiry-title">{{current.title}}</h2><p>{{current.category}}</p></header><div class="selected-summary"><div><span>FORMA</span><b>{{current.format}}</b></div><div><span>ZAKRES</span><b>{{current.scope}}</b></div><div><span>PROWADZENIE</span><b>{{current.trainer}}</b></div></div><form @submit.prevent="inquirySent=true"><div class="modal-row"><label><b>Imię i nazwisko</b><input required placeholder="Anna Kowalska"/></label><label><b>E-mail służbowy</b><input required type="email" placeholder="anna@firma.pl"/></label></div><div class="modal-row"><label><b>Firma lub instytucja</b><input placeholder="Nazwa organizacji"/></label><label><b>Liczba uczestników</b><input type="number" min="1" placeholder="np. 12"/></label></div><div class="modal-row"><label><b>Preferowana forma</b><select><option>Online</option><option>Stacjonarnie w naszej firmie</option><option>Stacjonarnie — potrzebujemy sali</option><option>Do ustalenia</option></select></label><label><b>Preferowany termin</b><input type="text" placeholder="np. październik 2026"/></label></div><label><b>Dodatkowe oczekiwania</b><textarea rows="3" placeholder="Poziom grupy, zagadnienia do uwzględnienia, branża..."></textarea></label><button type="submit">WYŚLIJ ZAPYTANIE O WYCENĘ <b>→</b></button></form></template><div v-else class="inquiry-success"><b>✓</b><h2>Zapytanie zapisane</h2><p>Wiemy, że interesuje Cię szkolenie „{{current.title}}”. Wrócimy z propozycją terminu i wyceną.</p><button @click="inquiryOpen=false">ZAMKNIJ</button></div></div></div></Teleport>
    <footer><span>© 2026 IMPERIAL ACADEMY</span><nav class="legal-links"><a href="./legal/polityka-prywatnosci.html">Polityka prywatności</a><a href="./legal/polityka-cookies.html">Polityka cookies</a><a href="./legal/regulamin.html">Regulamin</a></nav><a href="mailto:kontakt@imperialacademy.pl">KONTAKT@IMPERIALACADEMY.PL</a></footer>
  </div>
</template>
